server:
  port: 9001
spring:
  application:
    name: ribbon-consumer
eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.128:8001/eureka
management:
  endpoints:
    web:
      exposure:
        include: '*'