spring:
  application:
    name: eureka-client
server:
  port: 9001
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka
  instance:
    instance-id: eureka-client-${server.port}
    # 使用ip展示服务地址
    prefer-ip-address: true